### ISSUE TITLE
Auto format text shortcut key?

### ISSUE THREAD

**Issue by manuel-di-iorio** [YellowAfterlife/GMEdit#123]
Hi, what's the shortcut key to autoformat the code, like Shift+Alt+F in VS Code ?
Can it be enabled on file save ?

(Based on this issue https://github.com/YellowAfterlife/GMEdit/pull/7)

**Comment by YellowAfterlife** [comment]
I don't believe that the formatter is currently bound to any shortcut at all - over time it broke due to new tokens being introduced, and has had some limitations even before that.

Making a minimal plugin to invoke [gml_fmt](https://github.com/sanbox-irl/gml_fmt) on the current file can be a better way. You can get the path to the currently open tab via `$gmedit["gml.file.GmlFile"].current.path`.

**Comment by manuel-di-iorio** [comment]
Thanks
