### ISSUE TITLE
electron dependency

### ISSUE THREAD

**Issue by maiple** [YellowAfterlife/GMEdit#145]
## Background Information

I'm building the project myself on 64-bit Linux Mint 20 (which is basically Ubuntu).

## Issue

Running `npm install -g electron` was all I needed to do to launch the compiled project. However, the method listed in the readme didn't work for me:

- *Copying the electron binary from an existing installation of gmedit.*
  - Firstly, this required copying some set of the dependency libraries (such as libffmpeg), which I did, but it isn't clear what other files in that installation folder might also need to be copied. 
  - Even after copying all other files in the existing installation over to my bin/ folder, I get this error:
  
```
$ bin/electron

A JavaScript error occurred in the main process
Uncaught Exception:
~/git/GMEdit/bin/resources/app/main.js:39
                        windowWidth = config.app?.windowWidth ?? windowWidth
                                                 ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:815:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/browser_init.js:5709:12)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5716:30)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at electron/js2c/browser_init.js:84:18
```

 - *Downloading a pre-built electron 11.x binary*: I didn't try this, because `npm install -g electron` worked. However, when I went to the [link provided](https://github.com/electron/electron/releases) in the readme, it wasn't very obvious how to find an 11.x binary; I only found 12.x+ binaries (but I didn't search exhaustively)

## Proposals

1. List `npm install -g electron` as the preferred method for installing the electron dependency.

2. change the link to release page to either say that any version of electron 11.x+ is acceptable, or else link to an actual 11.x release tag.

**Comment by YellowAfterlife** [comment]
> Copying the electron binary from an existing installation of gmedit.

The README says "Alternatively, extract an existing GMEdit Beta to bin/ without replacing files.".  
You have both tried only copying a binary (which is not what README suggests) _and_ used a stable version, which uses a different major version of Electron (which are incompatible - more on this soon).

> However, when I went to the link provided in the readme, it wasn't very obvious how to find an 11.x binary; I only found 12.x+ binaries (but I didn't search exhaustively)

Unfortunately, Electron releases are a mishmash of different versions, so a 11.x release can be on the second or the third page. However, I'm pleased to inform that you are the first person to fail to find the release.

> say that any version of electron 11.x+ is acceptable

That is false - major versions of Electron may and do introduce [breaking changes](https://www.electronjs.org/docs/breaking-changes) to behaviour or API. For some GMEdit-specific examples:

* Sync/callback based dialog functions were at one point [replaced](https://www.electronjs.org/docs/breaking-changes#api-changed-callback-based-versions-of-promisified-apis) by Promise-based functions under the same names. This broke virtually every dialog box in the tool. Fortunately, I had not assumed a default value to be the confirmation in any of the cases.
* [Changes to what counts as same origin](https://github.com/electron/electron/issues/19789) with local files broke GMLive.js at some point and required [some unusual hacks](https://github.com/YellowAfterlife/GMEdit/blob/468d26592311ec12135806314e9462020a13c600/bin/resources/app/main.js#L69) to workaround.
* Electron 14 is [scheduled](https://github.com/electron/electron/issues/21408) to remove the `remote` module, which will cause all sorts of havoc (breaking menus, dialogs, path resolution, etc.) and require a new dependency to resolve.

> or else link to an actual 11.x release tag.

Ideally should be using the most recent release since incremental versions contain security improvements and fixes for variously bizarre issues ([example](https://github.com/microsoft/vscode/issues/107016)). I may look into automating the process of finding the latest fitting release tag if I ever run out of more useful things to do.

> List npm install -g electron as the preferred method for installing the electron dependency.

As per above, this would require either writing an extra tool or manually updating the `@version` number in the README, neither of which are things that I intend to do at the moment.
