### ISSUE TITLE
Args magic JSDocs break on multi-function scripts

### ISSUE THREAD

**Issue by adam-coster** [YellowAfterlife/GMEdit#89]
When a script has multiple functions, if we use args magic for a function its JSDocs comments appear at the top of the file. This was when using args magic in a function that had no other JSDocs, and where prior functions also had no JSDocs.

Expected that using args magic would cause the `/// @arg` comments to appear immediately above the function.

**Comment by YellowAfterlife** [comment]
Ultimately `#args` is obsolete in GMS2.3+ due to introduction of named function arguments. [`??=` operator](https://github.com/YellowAfterlife/GMEdit/wiki/Using-null-conditional-assignment) can be used for quickly specifying 2.3-compliant optional arguments and [`optional` plugin](https://github.com/nommiin/optional) by Nommiin is a good solution for anyone that wants their function declarations even more compact than that.
