### ISSUE TITLE
functions within create event for an object aren't picked up as functions

### ISSUE THREAD

**Issue by MsShill** [YellowAfterlife/GMEdit#91]
_Awesome project you have going on here! don't know what I'd do without multiple pointers in gml tbh_

Here's a minor annoyance I found:
```
#event create
function doStuff() <- does not get highlighted as a function
{
    //etc
}

#event step
doStuff() <- linter complains about missing function, this is not the case
```
The linter complains that functions within the create event, are missing in the step event, perhaps the linter does not register functions outside of scripts?
I have disabled inspecting for missing functions to resolve this temporarily, hopefully this can be fixed easily.

**Comment by KeeVeeGames** [comment]
For in-object functions, you should do:
```js
doStuff = function() {}
```
Declaration with the `function` at the beginning making it global.

**Comment by YellowAfterlife** [comment]
> <- does not get highlighted as a function

It will not be highlighted as a function¹, but I did push a commit that fixes auto-completion and argument info.

Here's a build (to be extracted over the current beta's files): [Editor-App-Only.zip](https://github.com/GameMakerDiscord/GMEdit/files/5660752/Editor-App-Only.zip)

¹ Since that is a choice between highlighting inside `with` blocks being blatantly incorrect and syntax highlighting becoming much more CPU-intensive due to parsing the code in search for `with` blocks. Neither are good.

> <- linter complains about missing function, this is not the case

Are you using the current version of GMEdit? I don't think that's been a thing for a while - in 2.3 the "missing function" warning basically never shows as you can never be sure that something doesn't get assigned a function using a less-obvious method.

**Comment by YellowAfterlife** [comment]
Haven't heard back but this is most likely fixed along with other changes in the new beta.
